{
  "success": false,
  "return_code": 1,
  "stdout": "\ud83c\udf19 Moon Dev: Long entry at 16737.38, size 45, SL 16512.68, TP 17186.78 \ud83d\ude80\n\n",
  "stderr": "Traceback (most recent call last):\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_package/T01_VolatilityDirectional_PKG.py\", line 111, in <module>\n    stats = bt.run()\n  File \"/opt/anaconda3/envs/tflow/lib/python3.10/site-packages/backtesting/backtesting.py\", line 1170, in run\n    strategy.next()\n  File \"/Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_package/T01_VolatilityDirectional_PKG.py\", line 78, in next\n    entry_price_pos = self.position.price\nAttributeError: 'Position' object has no attribute 'price'\n\nERROR conda.cli.main_run:execute(124): `conda run python /Users/md/Dropbox/dev/github/moon-dev-ai-agents-for-trading/src/data/rbi_pp/10_23_2025/backtests_package/T01_VolatilityDirectional_PKG.py` failed. (See above for error)\n",
  "execution_time": 1.355162,
  "timestamp": "2025-10-23T09:22:14.237740"
}